#!/bin/bash

# TaskRamen.ai
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jobs Jolt Private Limited (TaskRamen.ai)

# core/link-skills.sh — publish .agents/skills/* into .claude/skills/ so Claude
# Code auto-discovers them.
#
# Why this is generated rather than committed: these entries used to be symlinks
# tracked in git. Git stores a symlink as a file whose contents are the link
# target, and checks it out as a plain text file wherever core.symlinks is false
# — the default on Windows without Developer Mode. The skill then loads as a
# one-line text file containing a path, and silently does nothing. Generating
# them at install/boot works on every platform, and falls back to copying where
# symlinks are unavailable.
#
# Idempotent and safe to run on every boot: existing correct links are left
# alone, stale ones are replaced, and entries that no longer have a source in
# .agents/skills/ are removed. Anything a user added by hand that is neither a
# link into .agents/skills/ nor a previous copy of one is left untouched.
#
# Never fails: skill discovery is a convenience, not a boot requirement.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_HOME="${CLAUDE_HOME:-$(dirname "$SCRIPT_DIR")}"

SRC_DIR="$CLAUDE_HOME/.agents/skills"
DST_DIR="$CLAUDE_HOME/.claude/skills"

[[ -d "$SRC_DIR" ]] || exit 0
mkdir -p "$DST_DIR" 2>/dev/null || exit 0

linked=0
for src in "$SRC_DIR"/*/; do
    [[ -d "$src" ]] || continue
    name="$(basename "$src")"
    dst="$DST_DIR/$name"
    target="../../.agents/skills/$name"

    # Already the link we want — nothing to do.
    if [[ -L "$dst" && "$(readlink "$dst" 2>/dev/null)" == "$target" ]]; then
        linked=$((linked + 1))
        continue
    fi

    # Replace a stale link, a previous copy, or a plain file. A real directory
    # that is NOT a copy of ours is left alone rather than clobbered.
    if [[ -L "$dst" ]]; then
        rm -f "$dst"
    elif [[ -d "$dst" ]]; then
        if [[ -f "$dst/.taskramen-generated" ]]; then
            rm -rf "$dst"
        else
            echo "link-skills: $dst exists and was not generated by us — leaving it alone" >&2
            continue
        fi
    elif [[ -e "$dst" ]]; then
        # A regular file where a skill directory belongs. This is the exact
        # artifact this script exists to prevent: git checks a symlink out as a
        # text file containing its target wherever core.symlinks is false
        # (Windows without Developer Mode). Left in place it fails silently — the
        # skill "exists" but is a one-line file. Replace it.
        rm -f "$dst"
    fi

    if ln -s "$target" "$dst" 2>/dev/null; then
        linked=$((linked + 1))
    elif cp -r "$src" "$dst" 2>/dev/null; then
        # No symlink support (e.g. a Windows bind mount). Copy instead and mark
        # it so the next run knows it may refresh it.
        touch "$dst/.taskramen-generated" 2>/dev/null || true
        linked=$((linked + 1))
    else
        echo "link-skills: could not publish skill '$name'" >&2
    fi
done

# Drop entries whose source skill is gone (renamed or removed upstream).
for dst in "$DST_DIR"/*; do
    [[ -e "$dst" || -L "$dst" ]] || continue
    name="$(basename "$dst")"
    [[ -d "$SRC_DIR/$name" ]] && continue
    if [[ -L "$dst" ]]; then
        rm -f "$dst"
    elif [[ -f "$dst/.taskramen-generated" ]]; then
        rm -rf "$dst"
    fi
done

echo "link-skills: published $linked skill(s) into .claude/skills/"
exit 0
